name: CI for apps/web

on:
  pull_request:
    paths:
      - 'apps/web/**/*'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Generate Prisma Client
        run: pnpm run --filter @x-clone-2023/web generate

      - name: Typecheck
        run: pnpm run --filter @x-clone-2023/web typecheck

      - name: Lint
        run: pnpm run --filter @x-clone-2023/web lint

      - name: Test
        run: pnpm run --filter @x-clone-2023/web test
